image: "python:latest"

stages:
    - deploy

pip_deploy:
    stage: deploy
    script:
        - pip install twine build
        - python -m build
        - twine upload -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" dist/*
    only:
        - tags
